#!/usr/bin/env python3
# Generated by Haiven Compass.
# Do not edit directly.

import shutil
import subprocess
import sys
from pathlib import Path

root = Path.cwd()
shared_hook = root / ".haiven/hooks/haiven-constitution-check.py"
if shared_hook.exists() and shared_hook.resolve() != Path(__file__).resolve():
    sys.exit(subprocess.run([sys.executable, str(shared_hook)], cwd=root).returncode)

if (root / "package.json").exists() and shutil.which("pnpm"):
    subprocess.run(["pnpm", "haiven:check"], check=True)
elif shutil.which("haiven"):
    subprocess.run(["haiven", "check"], check=True)
else:
    print("haiven check not found. Install @haiven/compass or add pnpm haiven:check.")
