#!/usr/bin/env python3
# Generated by Haiven Compass.
# Do not edit directly.

import shutil
import subprocess
import sys
from pathlib import Path

CODE_EXTENSIONS = {".ts", ".tsx", ".js", ".jsx", ".go", ".py", ".cs", ".java", ".rb", ".php", ".rs"}
TEST_MARKERS = ("/test/", "/tests/", "__tests__", ".test.", ".spec.")
API_MARKERS = ("/api/", "controller", "handler", "route")
CONTRACT_MARKERS = ("openapi", "contract", "schema", "swagger")


def run_and_capture(cmd, cwd):
    try:
        res = subprocess.run(cmd, cwd=cwd, check=False, text=True, capture_output=True)
        return res.returncode, res.stdout
    except Exception:
        return 1, ""


def changed_files(root):
    commands = [
        ["git", "diff", "--name-only", "--cached"],
        ["git", "diff", "--name-only"],
    ]
    files = []
    seen = set()
    for cmd in commands:
        code, out = run_and_capture(cmd, root)
        if code != 0:
            continue
        for line in out.splitlines():
            item = line.strip().replace("\\", "/")
            if item and item not in seen:
                seen.add(item)
                files.append(item)
    return files


def looks_like_test(path):
    lower = path.lower()
    if any(marker in lower for marker in TEST_MARKERS):
        return True
    base = Path(lower).name
    return base.startswith("test_")


def looks_like_code(path):
    return Path(path).suffix.lower() in CODE_EXTENSIONS


def looks_like_api(path):
    lower = path.lower()
    return any(marker in lower for marker in API_MARKERS)


def looks_like_contract(path):
    lower = path.lower()
    return any(marker in lower for marker in CONTRACT_MARKERS)


def run_haiven_check(root):
    if (root / "package.json").exists() and shutil.which("pnpm"):
        code, _ = run_and_capture(["pnpm", "haiven:check"], root)
        if code == 0:
            return 0
    if shutil.which("haiven"):
        code, _ = run_and_capture(["haiven", "check"], root)
        return code
    local_compass = root / "packages" / "compass" / "bin" / "haiven.js"
    if local_compass.exists() and shutil.which("node"):
        code, _ = run_and_capture(["node", str(local_compass), "check"], root)
        return code
    print("haiven check not found. Install @haiven/compass or add pnpm haiven:check.")
    return 0


def main():
    root = Path.cwd()
    files = changed_files(root)
    code_files = [f for f in files if looks_like_code(f)]
    test_files = [f for f in files if looks_like_test(f)]
    api_files = [f for f in code_files if looks_like_api(f)]
    contract_files = [f for f in files if looks_like_contract(f)]

    print("[haiven] constitution hook")
    print(f"[haiven] changed files detected: {len(files)}")

    failures = []
    notices = []

    if code_files and not test_files:
        failures.append("Code changed without test changes. Haiven Constitution section 6 requires test-first delivery.")

    if api_files and not contract_files:
        notices.append("API-like files changed without obvious contract file updates. Confirm section 4 (contract-first).")

    if notices:
        print("[haiven] notices:")
        for item in notices:
            print(f"- {item}")

    if failures:
        print("[haiven] failures:")
        for item in failures:
            print(f"- {item}")
        return 1

    return run_haiven_check(root)


if __name__ == "__main__":
    sys.exit(main())
